// Marketing copy is isolated from the authenticated workspace.
export const landingCopy = {
  en: {
    nav: ['The possibilities', 'How it works', 'Questions'], menu: 'Open navigation', close: 'Close navigation',
    eyebrow: 'A little automation. A lot more conversation.',
    title: ['Make content.', 'Leave room for', 'connection.'],
    intro: 'Your next conversation starts with a comment. Give it a thoughtful reply, a useful link, and a next step. Without doing it all by hand.',
    cta: 'Create your first flow', watch: 'See it in motion', note: 'For Instagram Business & Creator accounts',
    edition: 'THE CONVERSATION STUDIO', demo: 'A comment. A connection.', demoNote: 'Illustrative example. No real messages are sent.',
    play: 'Play example', pause: 'Pause example', replay: 'Replay example',
    stages: ['Choose a post', 'A comment arrives', 'Your rule matches', 'A DM is prepared'],
    postLabel: 'YOUR SELECTED POST', postTitle: ['THE', 'CREATOR', 'EDIT.'], postCaption: 'A small guide to your next big idea.',
    visitor: 'A curious follower', comment: 'Can I get the guide?', keyword: 'guide', match: 'Keyword matched',
    messageLabel: 'YOUR MESSAGE', message: 'Of course! Here is the guide you asked for.', messageLink: 'Open the guide',
    principles: ['No code. Just your words.', 'A flow for each post.', 'You stay in control.'],
    howLabel: '01 / FROM INTEREST TO CONVERSATION', howTitle: ['You set the tone.', 'Your flow takes it from there.'],
    steps: [
      { title: 'Bring your account.', body: 'Connect your professional account through Instagram. Your password never comes to us.' },
      { title: 'Give one post a purpose.', body: 'Pick a post, a keyword, and the reply people should receive. Nothing goes live until you activate it.' },
      { title: 'Keep the conversation moving.', body: 'New comments trigger your rule. Review replies, messages, and delivery issues in your workspace.' },
    ],
    featuresLabel: '02 / LESS REPETITION. MORE YOU.', featuresTitle: ['Make it personal.', 'Even when it is automatic.'],
    features: [
      { title: 'Your post. Your rules.', body: 'A launch, a tutorial, a new collection. Give each selected post its own keyword and response.' },
      { title: 'Sound like yourself.', body: 'Write a public reply, an opening message, or a useful link. The words are yours, not a generic script.' },
      { title: 'Know what actually happened.', body: 'See matched rules, completed actions, and failures. A prepared message is not the same as a delivered one.' },
    ],
    specimenLabel: 'YOUR WORDS, CONNECTED', specimenWord: 'Curiosity', specimenTags: ['The guide', 'The details', 'The next drop'], specimenFoot: 'One thoughtful next step.',
    trustTitle: 'Your account stays yours.', trustBody: 'Connect through Instagram, choose what runs, and disconnect when you want. Delivery depends on account permissions and Instagram policies.', trustLink: 'How we handle your data',
    faqLabel: 'A FEW GOOD QUESTIONS', faqTitle: 'Before the first hello.',
    questions: [
      { title: 'Which Instagram accounts can connect?', body: 'Instagram Business and Creator accounts. A personal account needs to switch to a professional account first. Available actions depend on the permissions granted to the app.' },
      { title: 'Does the example send a real message?', body: 'No. The animation is only an explanation. It does not connect to Instagram, post a comment, or send a DM.' },
      { title: 'Will it message everyone on my account?', body: 'No. You choose the post, trigger, and actions. Only eligible events matching your active rules are processed, within Instagram restrictions and your plan limits.' },
      { title: 'Can I get started for free?', body: 'Yes. You can create a free account. Your workspace shows your usage and plan limits. Paid upgrades are not currently enabled.' },
    ],
    finalLabel: 'MAKE SPACE FOR WHAT YOU CREATE.', finalTitle: ['Less repeating.', 'More connecting.'], finalCta: 'Start with one post', finalNote: 'Your words. Your audience. Your next chapter.',
    legal: 'Built for creators. Not affiliated with Instagram or Meta.',
  },
  ar: {
    nav: ['ماذا يمكنك أن تفعل؟', 'كيف يعمل؟', 'أسئلة شائعة'], menu: 'فتح التنقل', close: 'إغلاق التنقل',
    eyebrow: 'أتمتة أقل تعقيدًا. محادثات أكثر معنى.', title: ['اصنع المحتوى.', 'واترك مساحة', 'للحوار.'],
    intro: 'خلف كل تعليق شخص مهتم. استقبله برد يشبهك، ورابط يفيده، وخطوة تفتح الحديث. بدون أن تكرر كل شيء بنفسك.',
    cta: 'أنشئ أول أتمتة', watch: 'شاهد الفكرة تتحرك', note: 'لحسابات Instagram للأعمال وصنّاع المحتوى',
    edition: 'مساحة للمحادثات التي تبدأ منك', demo: 'من تعليق… إلى حوار.', demoNote: 'مثال توضيحي فقط. لا تُرسل أي رسائل حقيقية.',
    play: 'تشغيل المثال', pause: 'إيقاف الحركة', replay: 'إعادة التجربة', stages: ['اختر منشورًا', 'يصل تعليق', 'تتطابق القاعدة', 'تُجهّز الرسالة'],
    postLabel: 'المنشور الذي اخترته', postTitle: ['فكرة.', 'تستحق', 'المشاركة.'], postCaption: 'دليل صغير لفكرتك الكبيرة القادمة.',
    visitor: 'متابع مهتم', comment: 'ممكن ترسل لي الدليل؟', keyword: 'الدليل', match: 'تطابقت الكلمة',
    messageLabel: 'رسالة بصوتك', message: 'بالتأكيد! هذا رابط الدليل الذي طلبته.', messageLink: 'افتح الدليل',
    principles: ['بدون كود. بكلماتك أنت.', 'لكل منشور رحلته.', 'القرار دائمًا لك.'],
    howLabel: '٠١ / من الاهتمام إلى المحادثة', howTitle: ['أنت تبدأ الفكرة.', 'والأتمتة تكمل معك.'],
    steps: [
      { title: 'ابدأ بحسابك.', body: 'اربط حسابك الاحترافي من خلال Instagram نفسه. كلمة مرور حسابك لا تصل إلينا.' },
      { title: 'امنح المنشور خطوة تالية.', body: 'اختر المنشور والكلمة المفتاحية، واكتب الرد الذي تريد أن يصل. لا تعمل القاعدة حتى تفعّلها.' },
      { title: 'اترك مجالًا للحوار.', body: 'تُشغّل التعليقات الجديدة قواعدك. تابع الردود والرسائل وأي تعثّر في التسليم من مساحة عملك.' },
    ],
    featuresLabel: '٠٢ / تكرار أقل. مساحة أكبر لك.', featuresTitle: ['اجعلها شخصية.', 'حتى لو كانت تلقائية.'],
    features: [
      { title: 'منشورك. وقواعدك.', body: 'إطلاق جديد، شرح مفيد، أو مجموعة منتجات. امنح كل منشور تختاره كلمة مفتاحية وردًا يناسبه.' },
      { title: 'كلمات تشبهك.', body: 'اكتب تعليقًا عامًا أو رسالة افتتاحية أو أرسل رابطًا مفيدًا. أنت تختار الكلمات، لا نص جاهز يُفرض عليك.' },
      { title: 'اعرف ما حدث فعلًا.', body: 'شاهد القواعد المطابقة والإجراءات المكتملة وأسباب التعثّر. تجهيز رسالة ليس دليلًا على وصولها.' },
    ],
    specimenLabel: 'كلماتك تفتح الحديث', specimenWord: 'فضول', specimenTags: ['الدليل', 'التفاصيل', 'الجديد القادم'], specimenFoot: 'وخطوة تالية تستحق.',
    trustTitle: 'حسابك يظل حسابك.', trustBody: 'اربطه عبر Instagram، وحدّد ما يعمل، وألغِ الربط متى أردت. يخضع التسليم لأذونات الحساب وسياسات Instagram.', trustLink: 'كيف نتعامل مع بياناتك؟',
    faqLabel: 'إجابات قبل أول محادثة', faqTitle: 'لنبدأ على وضوح.',
    questions: [
      { title: 'ما الحسابات التي يمكن ربطها؟', body: 'حسابات Instagram للأعمال وصنّاع المحتوى. يجب تحويل الحساب الشخصي إلى احترافي أولًا. تعتمد الإجراءات المتاحة على الأذونات الممنوحة للتطبيق.' },
      { title: 'هل التجربة هنا تُرسل رسالة حقيقية؟', body: 'لا. الحركة في هذه الصفحة لشرح الفكرة فقط. لا تتصل بحساب Instagram ولا تنشر تعليقًا ولا ترسل رسالة.' },
      { title: 'هل سيراسل التطبيق جميع متابعيّ؟', body: 'لا. أنت تختار المنشور والمحفّز والإجراءات. تُعالَج الأحداث المؤهلة المطابقة لقواعدك المفعّلة فقط، ضمن قيود Instagram وحدود خطتك.' },
      { title: 'هل يمكنني البدء مجانًا؟', body: 'نعم، يمكنك إنشاء حساب مجاني. تظهر حدود خطتك واستهلاكك في مساحة العمل. الترقيات المدفوعة غير مفعّلة حاليًا.' },
    ],
    finalLabel: 'مساحة أكبر لما تحب أن تصنعه.', finalTitle: ['كرّر أقل.', 'تواصل أكثر.'], finalCta: 'ابدأ بمنشور واحد', finalNote: 'كلماتك. جمهورك. والبداية القادمة.',
    legal: 'صُمّم لصنّاع المحتوى. غير تابع لـInstagram أو Meta.',
  },
};
